# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 19:19
from __future__ import unicode_literals

import admin_panel.user_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', admin_panel.user_manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
    ]
