# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Название')),
                ('article_text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Название')),
                ('index_page', models.CharField(max_length=200, verbose_name='Ссылка на индексную страницу')),
                ('parent_catalog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simpleDjango.Catalog', verbose_name='Родительский каталог')),
            ],
        ),
    ]
