# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('article_text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('is_index', models.BooleanField(verbose_name='Индексная?')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('parent_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleDjango.Catalog', verbose_name='Родительский каталог')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleDjango.Catalog', verbose_name='Каталог'),
        ),
    ]
