# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleDjango', '0004_auto_20170712_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catalog',
            field=models.ForeignKey(default='/', on_delete=django.db.models.deletion.CASCADE, to='simpleDjango.Catalog', verbose_name='Каталог'),
        ),
    ]
